version: '3.1'

services:
  postgres:
    image: postgres:14-alpine3.17
    ports:
      - "5432:5432"
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  script:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./local.env
    command: python start_script.py

volumes:
  postgres_data:
